package alexgr.taskmanagement.entity;

import alexgr.taskmanagement.dto.role.Role;
import jakarta.persistence.*;
import lombok.Data;
/**
 * Represents a role entity in the database.
 * <p>
 * This entity maps roles to the `roles` table and is used to assign user roles, such as `USER` or `ADMIN`.
 * </p>
 */
@Entity
@Data
@Table(name = "roles")
public class RoleEntity {
    /**
     * The unique identifier for the role.
     * <p>
     * This value is automatically generated by the database.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * The name of the role.
     * <p>
     * This field is an enumerated type and ensures only predefined roles are stored in the database.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role_name", unique = true)
    private Role role;
}
